### ISSUE TITLE
Unitialized Value in cValGesInit

### ISSUE THREAD

**Issue by luc-girod** [micmacIGN/micmac#13]
Hei,

I am compiling on Windows with Visual Studio 2015 and the simplest Tapioca command (even in the Gravillon dataset) fails with :+1: 

------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened
|
|    Unitialized Value in cValGesInit
|
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :
|
| Error was detected
|          at line : 824
|          of file : c:\git\micmac\include\general/util.h
-------------------------------------------------------------
Bye  (press enter)

I have no idea what Value it's talking about, the dataset normally works fine.

**Comment by ToroCat** [comment]
Regrading to the source of rev 5ec4a62, I think the two assertion in functions(line 822 & line 838):

`const Type & Val() const`

and

`Type & Val()`

should be embraced by 

`if (!mIsInit){}`

**Comment by luc-girod** [comment]
Well, testing the Boolean value of mIsInit is what `ELISE_ASSERT(mIsInit,"Unitialized Value in cValGesInit");` is doing (Either mIsInit=True or print "Unitialized Value in cValGesInit" and break).

**Comment by ToroCat** [comment]
Yes, but at least using the if() clause will not make the programme cease even the condition is false. And that is what `const Type & Val(const std::string aMes ) const` do(in line 827).

I notice that at line 799, there is an initialization for `mVal`, but is commented out by saying that "Bug Windows". This bug obviously caused by using cTplValGesInit instance without initialization, tracing the calling stake may be a good choice.(I will try to dive into see what happen in a few day).

**Comment by luc-girod** [comment]
Arg, I feel a bit dumb now:
MicMac needs to be compiled in a subfolder of the folder containing /include and such, otherwise, it cannot find them...and gives this error (basically, "couldn't find xml templates for camera files", or something like that).
So the fix is to not let Visual Studio decide where to compile and force to compilation of both mm3d and SaisieQT in micmac/bin .
