### ISSUE TITLE
How to use Rolling Shutter correction ?

### ISSUE THREAD

**Issue by kikislater** [micmacIGN/micmac#142]
Hi,
I saw these commits : 
https://github.com/micmacIGN/micmac/commit/8a5b8758da8410d7ad9fcdc433b671aacb808a31

https://github.com/micmacIGN/micmac/commit/a092bfdec87f56d4a84da723f6cab4ae47bb4cbc

https://github.com/micmacIGN/micmac/commit/1ae9612763ac3a8993aeb8aa7c542051990dee99

Unfortunately it's not in documentation ... 
Could someone give guidance in how to use it ? May be @YilinZHOU ?

**Comment by YilinZHOU** [comment]
Hi,

Please find below a brief presentation of the rolling shutter correction implemented in MicMac, it is an experimental function and is still under development.

Could you keep me posted on your processing results? It will help me improve the function.

Firstly, the readout time of the camera should be known for future image correction. I calibrated myself the camera of DJI Mavic 2 Pro, of which the readout time is around 56ms.

https://www.pix4d.com/blog/rolling-shutter-correction gives the readout time for some other commonly used cameras.

Rolling Shutter Correction :

1. Estimate the camera velocity at exposure for each image

Since the rolling shutter distortion is related to camera motion, it is essential to know or to estimate the camera velocity. In MicMac, one can do it with the command
-------------------------------------------------------------------------------
mm3d XifDate2Txt "image_pattern" CalVOri="sensor_orientation"
-------------------------------------------------------------------------------

The idea is to firstly extract time-related information of each image from the metadata. The camera velocity of camera i is estimated as the ratio of camera position change and time interval between camera i − 1 and camera i + 1. The camera positions are given in the form of an Ori folder in MicMac. The Ori folder can be issued from Tapas (it is recommended to georeference the Ori folder with GCPBascule or CenterBascule) as well as OriConvert (the GNSS data are used to created the Ori folder, however, a calibration file AutoCalib-xxxxx is needed to be included in the folder before performing XifDate2Txt). One should bear in mind that the estimation is on a strip basis, which means the given image pattern should represent a quasi-constant translational motion of the drone. Personally, I perform this command for each strip with a loop script, and merge the output files afterwards.

2. Correct the observations impacted by the rolling shutter effect

The correction of rolling shutter effect is done with the command TestLib ReechRolShut on tie points and image measurements.
-------------------------------------------------------------------------------
mm3d TestLib ReechRolShut "image_pattern"  "sensor_orientation" "readout_time" "camera_velocity_file" SHIn="tie_points_to_be_corrected" MAFIn="image_measurements_to_be_corrected"
-------------------------------------------------------------------------------

The readout_time given to the command is of unit us/line, not for the whole image (i.e. readout_time/#_of_line). The camera_velocity_file is the one issued from the last step. With this command, the tie points and the image measurements are corrected with respect to the camera motion at exposure.

It is a function that is far from being mature. Please do not hesitate if you have any questions.

Best regards.

Yilin @ MicMac

Le 2 nov. 2019 à 06:55, Sylvain POULAIN <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi,
I saw these commits :
8a5b875<https://github.com/micmacIGN/micmac/commit/8a5b8758da8410d7ad9fcdc433b671aacb808a31>

a092bfd<https://github.com/micmacIGN/micmac/commit/a092bfdec87f56d4a84da723f6cab4ae47bb4cbc>

1ae9612<https://github.com/micmacIGN/micmac/commit/1ae9612763ac3a8993aeb8aa7c542051990dee99>

Unfortunately it's not in documentation ...
Could someone give guidance in how to use it ? May be @YilinZHOU<https://github.com/YilinZHOU> ?

**Comment by kikislater** [comment]
Thank you for the long explanation. I will definitively try it ! 
How do you calibrate your camera to know sensor readout ? 

Does you work is related to these recents papers :
https://arxiv.org/pdf/1903.03943.pdf

http://openaccess.thecvf.com/content_cvpr_2018/papers/Lao_A_Robust_Method_CVPR_2018_paper.pdf

Best regards

**Comment by YilinZHOU** [comment]
CONFIDENTIAL & RESTRICTED

Hi Sylvain,

Sorry for the very late reply. I am actually preparing my PhD defence so I forget a lot of things.

My work is not related to the papers you listed, I just submitted one paper about rolling shutter correction and will be published soon. If you have access to ISPRS journal you will find it there.

Otherwise, my PhD defence will take place the 6th December in Paris. I don't know if you are in Paris, but it is public and you are welcomed. Afterwards, I can send you my thesis in which you will find most of the information needed.

Best regards.

Yilin

**Comment by kikislater** [comment]
Hi Yilin,

I will not be in Paris on 6th of december but will be glad to read your thesis ! 
Good luck for presenting your PhD.

See you !

**Comment by devernay** [comment]
Yilin's thesis is available there: https://tel.archives-ouvertes.fr/tel-02474315

**Comment by WanpengShao** [comment]
Hi, 你好打扰了，我想请问一下 你用的数据格式是什么，我用的数据是从大疆无人机摄影 然后采集的视频帧，然后用micmac来跑，接着用你说的mm3d XifDate2Txt "image_pattern" CalVOri="sensor_orientation" 去跑 结果 得到的XifDate.txt  都是 frame_0001.jpg 0:0:0 -100/-100/0
frame_0021.jpg 0:0:0 -100/-100/0
frame_0041.jpg 0:0:0 -100/-100/0
frame_0061.jpg 0:0:0 -100/-100/0
frame_0081.jpg 0:0:0 -100/-100/0
frame_0101.jpg 0:0:0 -100/-100/0
frame_0121.jpg 0:0:0 -100/-100/0
frame_0141.jpg 0:0:0 -100/-100/0
frame_0161.jpg 0:0:0 -100/-100/0
frame_0181.jpg 0:0:0 -100/-100/0
frame_0201.jpg 0:0:0 -100/-100/0
frame_0221.jpg 0:0:0 -100/-100/0
frame_0241.jpg 0:0:0 -100/-100/0
frame_0261.jpg 0:0:0 -100/-100/0
frame_0281.jpg 0:0:0 -100/-100/0
frame_0301.jpg 0:0:0 -100/-100/0
frame_0321.jpg 0:0:0 -100/-100/0
frame_0341.jpg 0:0:0 -100/-100/0
frame_0361.jpg 0:0:0 -100/-100/0
frame_0381.jpg 0:0:0 -100/-100/0
frame_0401.jpg 0:0:0 -100/-100/0
frame_0421.jpg 0:0:0 -100/-100/0
frame_0441.jpg 0:0:0 -100/-100/0
frame_0461.jpg 0:0:0 -100/-100/0
frame_0481.jpg 0:0:0 -100/-100/0
frame_0501.jpg 0:0:0 -100/-100/0
frame_0521.jpg 0:0:0 -100/-100/0
frame_0541.jpg 0:0:0 -100/-100/0 
frame_0561.jpg 0:0:0 -100/-100/0   然后我发现我的数据micmac XML时间戳都是错误的  <Time>-1.00000000000000002e+30</Time>  但是我文件的时间戳是我明明从wrt文件里面给补充进照片里面的。怎么会没有呢？  而且我用micmac文件 set Exif的时候。 会出现这个错误：  ERROR: 
Error: Directory Photo: Next pointer is out of bounds; ignored.
Warning: Directory (Last IFD item), entry 0x0000 has unknown Exif (TIFF) type 57; setting type size 1.
Error: Directory (Last IFD item), entry 0x0000 has invalid size 2284126212*1; skipping entry.
Error: (Last IFD item) pointer references previously read GPSInfo directory. Ignored. 所以我想知道你那边处理的时候用的数据是什么格式的。

**Comment by WanpengShao** [comment]
Hi , Dr. Zhou, 

I am working on RS correction research. 
I am trying to using your method to correct my UAV data. 
I have get the dense point clouds after running C3DC. 
I get many files in ![Image](https://github.com/user-attachments/assets/edf543b6-78ec-4790-a7ea-63e84887c652).
When I am running this : 
mm3d TestLib ReechRolShut "DJI_(050[1-9]|051[0-7]).JPG"  Ori-GCPBascPredicOut 12.5 CalcV.txt SHIn=Homol MAFIn=PredicImageMeasurements-S3D.xml
"DJI_(050[1-9]|051[0-7]).JPG": 17 matches.
aCalcV : 0 files
So I do not know what's wrong with the my args_in.
And I also do not know how to get the quality report of the dense points. 

BR
 Shao
